
trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
- script: |
    echo Fetching Flyway Project
    $ flyway -password=Snowflake@dmin  info
    dir
  displayName: 'Fetch Flyway Project'
